CREATE TABLE IF NOT EXISTS genres (
   id INTEGER PRIMARY KEY,
   name varchar(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS  ratings  (
 id INTEGER PRIMARY KEY,
 name varchar(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id INTEGER,
  genre_id INTEGER,
  PRIMARY KEY ( film_id ,  genre_id )
);

CREATE TABLE IF NOT EXISTS  films  (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(300),
  description varchar(2000),
  release_date timestamp,
  duration integer,
  rating_id integer
);

CREATE TABLE IF NOT EXISTS  users  (
   id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   email  varchar(50),
   login  varchar(50) NOT NULL,
   name  varchar(50),
   birthday  varchar(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS friends  (
   user_id  integer,
   friend_id  integer,
   PRIMARY KEY ( user_id ,  friend_id )
);

CREATE TABLE IF NOT EXISTS likes  (
    user_id  integer,
    film_id  integer,
    PRIMARY KEY ( user_id ,  film_id )
);

ALTER TABLE IF EXISTS films DROP CONSTRAINT IF EXISTS fk_film_rating;
ALTER TABLE IF EXISTS friends DROP CONSTRAINT IF EXISTS fk_friends_user_id;
ALTER TABLE IF EXISTS friends DROP CONSTRAINT IF EXISTS fk_friends_user_friend_id;
ALTER TABLE IF EXISTS likes DROP CONSTRAINT IF EXISTS fk_likes_users;
ALTER TABLE IF EXISTS likes DROP CONSTRAINT IF EXISTS fk_likes_films;
ALTER TABLE IF EXISTS film_genres DROP CONSTRAINT IF EXISTS fk_film_genres_films;
ALTER TABLE IF EXISTS film_genres DROP CONSTRAINT IF EXISTS fk_film_genres_genres;

ALTER TABLE films
    ADD CONSTRAINT fk_film_rating FOREIGN KEY ( rating_id ) REFERENCES ratings ( id );

ALTER TABLE friends
    ADD CONSTRAINT fk_friends_user_id FOREIGN KEY (friend_id) REFERENCES users (id);

ALTER TABLE friends
    ADD CONSTRAINT fk_friends_user_friend_id FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE likes
    ADD CONSTRAINT fk_likes_users FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE likes
    ADD CONSTRAINT fk_likes_films FOREIGN KEY (film_id) REFERENCES films (id);

ALTER TABLE film_genres
    ADD CONSTRAINT fk_film_genres_films FOREIGN KEY (film_id) REFERENCES films (id);

ALTER TABLE film_genres
    ADD CONSTRAINT fk_film_genres_genres FOREIGN KEY (genre_id) REFERENCES genres (id);